from tkinter import *
import pyautogui
from time import sleep
import subprocess

root = Tk()

root.title("Paint Bot")

root.geometry("310x120")

def bot():

    subprocess.Popen(r"C:\Windows\system32\mspaint.exe")

    sleep(1)

    # For Help: pyautogui.displayMousePosition()

    #head
    pyautogui.moveTo(440,196)
    pyautogui.dragRel(150,0)
    pyautogui.dragRel(0,100)
    pyautogui.dragRel(-150,0)
    pyautogui.dragRel(0,-100)
    pyautogui.dragRel(0,100)
    pyautogui.dragRel(50,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(60,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(120,0)
    pyautogui.dragRel(0,200)
    #left hand
    pyautogui.dragRel(-2,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(-2,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(-2,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(-2,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(-2,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(53,0)
    pyautogui.dragRel(-55,0)
    pyautogui.dragRel(0,-150)
    pyautogui.dragRel(-35,0)
    #body
    pyautogui.dragRel(0,300)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-55,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(55,0)
    pyautogui.dragRel(-40,0)
    pyautogui.dragRel(0,-100)
    pyautogui.dragRel(-45,0)
    pyautogui.dragRel(0,100)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-55,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(55,0)
    pyautogui.dragRel(-40,0)
    pyautogui.dragRel(0,-300)
    #right hand
    pyautogui.dragRel(-35,0)
    pyautogui.dragRel(0,150)
    pyautogui.dragRel(-2,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(-2,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(-2,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(-2,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(-2,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(53,0)
    pyautogui.dragRel(-55,0)
    pyautogui.dragRel(0,-200)
    pyautogui.dragRel(120,0)
    # #face
    pyautogui.moveTo(470,228)
    pyautogui.dragRel(20,0)
    pyautogui.moveTo(532,228)
    pyautogui.dragRel(20,0)
    pyautogui.moveTo(494,270)
    pyautogui.dragRel(4,0)
    pyautogui.dragRel(0,3)
    pyautogui.dragRel(4,0)
    pyautogui.dragRel(0,3)
    pyautogui.dragRel(4,0)
    pyautogui.dragRel(0,3)
    pyautogui.dragRel(4,0)
    pyautogui.dragRel(0,3)
    pyautogui.dragRel(4,0)
    pyautogui.dragRel(0,-3)
    pyautogui.dragRel(4,0)
    pyautogui.dragRel(0,-3)
    pyautogui.dragRel(4,0)
    pyautogui.dragRel(0,-3)
    pyautogui.dragRel(4,0)
    pyautogui.dragRel(0,-3)
    pyautogui.dragRel(4,0)

    #hair
    pyautogui.moveTo(443,196)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,-30)
    pyautogui.dragRel(5,0)
    pyautogui.dragRel(0,30)
    pyautogui.moveTo(505,251)
    pyautogui.dragRel(13,0)
    #abs
    pyautogui.moveTo(519,395)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-25,0)
    pyautogui.dragRel(50,0)
    pyautogui.dragRel(-25,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-25,0)
    pyautogui.dragRel(50,0)
    pyautogui.dragRel(-25,0)
    pyautogui.dragRel(0,30)
    pyautogui.dragRel(-25,0)
    pyautogui.dragRel(50,0)
    pyautogui.dragRel(-25,0)
    pyautogui.dragRel(0,30)
    pyautogui.screenshot("myPythonPaintBot.png")

# print on app
Label(root, text = "  ").grid(column=0, row=0)
Label(root, text = "Click : ").grid(column=0, row=1)

# button to start drawing
btn = Button(root, text = "Open Paint & Start Drawing", command = bot).grid(column=1,row=1)

# print on app
Label(root, text = "  ").grid(column=0, row=2)
Label(root, text = "Developer: Kumar Anurag").grid(column=0, row=3)
Label(root, text = "Instagram: kmranrg").grid(column=0, row=4)

root.mainloop()

